export const SET_NUMBER_OF_MOVES = 'SET_NUMBER_OF_MOVES';
export const SELECT_CUBE = 'SELECT_CUBE';
export const CUBE_OPEN = 'CUBE_OPEN';
export const SET_SELECTED_CUBE = 'SET_SELECTED_CUBE';
export const SET_LUCKY_MOVE = 'SET_LUCKY_MOVE';
export const REMOVE_SELECTED = 'REMOVE_SELECTED';
export const RETURN_PREV_CUBES = 'RETURN_PREV_CUBES';
